// Import semua ikon dari library (misal, @icon-park/react)
import {
	AirVent,
	Ambulance,
	BadgeCheck,
	BedDouble,
	Beef,
	Binoculars,
	Blinds,
	Book,
	Cake,
	Calendar,
	Camera,
	Car,
	CarFront,
	Cctv,
	Cigarette,
	CircleX,
	Cross,
	Dumbbell,
	EggFried,
	Fan,
	Film,
	Flame,
	GraduationCap,
	Hand,
	HandCoins,
	HandPlatter,
	LampCeiling,
	MoonStar,
	Refrigerator,
	Shirt,
	ShoppingCart,
	ShowerHead,
	Smile,
	Sparkle,
	SquareDot,
	Sunset,
	Toilet,
	TreePine,
	Trees,
	TvMinimal,
	TvMinimalPlay,
	Utensils,
	WashingMachine,
	WavesLadder,
	Wifi,
} from "lucide-react";

// Mapping kategori dan item ke komponen
export const facilities = [
	{
		id: "k1",
		category: "Pemandangan Indah",
		items: [
			{ id: "1", icon: TreePine, label: "Pemandangan taman" },
			{ id: "2", icon: Sunset, label: "Pemandangan sunset" },
		],
	},
	{
		id: "k2",
		category: "Kamar Tidur",
		items: [
			{
				id: "3",
				icon: BedDouble,
				label: "Empat kamar sejuk dengan twin bed/king size",
			},
			{ id: "4", icon: BadgeCheck, label: "Handuk tersedia" },
			{ id: "5", icon: AirVent, label: "AC dingin berpurifier" },
			{ id: "6", icon: Shirt, label: "Lemari Pakaian" },
			{ id: "7", icon: Blinds, label: "Gorden penutup cahaya" },
			{ id: "8", icon: LampCeiling, label: "Cahaya lampu mewah" },
		],
	},
	{
		id: "k3",
		category: "Fasilitas Olahraga",
		items: [
			{ id: "9", icon: Dumbbell, label: "Gym corner" },
			{ id: "10", icon: WavesLadder, label: "Kolam renang" },
		],
	},
	{
		id: "k4",
		category: "Area Anak-anak",
		items: [{ id: "11", icon: Smile, label: "Mini indoor playground" }],
	},
	{
		id: "k5",
		category: "Fasilitas Bersama",
		items: [
			{
				id: "12",
				icon: TvMinimal,
				label: "2 televisi",
				description: "Televisi di setiap lantai",
			},
			{ id: "13", icon: Utensils, label: "2 dapur" },
			{ id: "14", icon: HandPlatter, label: "Meja makan luas" },
			{ id: "15", icon: Refrigerator, label: "Kulkas" },
			{ id: "16", icon: WashingMachine, label: "Mesin cuci elektrolux" },
			{
				id: "17",
				icon: Wifi,
				label: "Wifi cepat dan stabil",
				description:
					"Kami menggunakan internet dengan kecepatan 100Mbps dengan pengguna ideal sebanyak 8 device",
			},
			{ id: "18", icon: Book, label: "Buku bacaan" },
		],
	},
	{
		id: "k6",
		category: "Kamar Mandi",
		items: [
			{ id: "19", icon: Toilet, label: "Toilet Duduk" },
			{ id: "20", icon: CarFront, label: "Garasi mobil" },
			{ id: "21", icon: HandCoins, label: "Shampoo" },
			{ id: "22", icon: HandCoins, label: "Sabun Mandi" },
			{ id: "23", icon: Fan, label: "Kipas ventilator" },
			{
				id: "24",
				icon: Flame,
				label: "Air Panas",
				description: "Dengan teknologi tenaga surya",
			},
			{ id: "25", icon: ShowerHead, label: "Empat kamar mandi" },
			{ id: "26", icon: ShowerHead, label: "Shower" },
		],
	},
	{
		id: "k7",
		category: "Area merokok",
		items: [
			{
				id: "27",
				icon: Cigarette,
				label: "Area merokok outdoor",
				description: "Area khusus merokok yang terpisah dari ruang utama.",
			},
		],
	},
	{
		id: "k8",
		category: "Keamanan",
		items: [
			{
				id: "28",
				icon: Cctv,
				label: "Kamera keamanan",
				description:
					"Kamera keamanan mengelilingi semua ruangan rumah kecuali kamar tidur.",
			},
			{ id: "29", icon: Ambulance, label: "Kotak P3K" },
		],
	},
	{
		id: "k9",
		category: "Hiburan",
		items: [{ id: "30", icon: TvMinimalPlay, label: "Netflix" }],
	},
	{
		id: "k10",
		category: "Dapur dan ruang makan",
		items: [
			{ id: "31", icon: Refrigerator, label: "Kulkas" },
			{
				id: "32",
				icon: Utensils,
				label: "Perlengkapan dasar memasak",
				description: "Panci dan wajan, minyak, sotel",
			},
			{
				id: "33",
				icon: Utensils,
				label: "Piring dan perangkat makan",
				description: "Mangkuk, sumpit, piring, cangkir, dll.",
			},
			{ id: "34", icon: Flame, label: "Kompor Gas dua tungku" },
			{ id: "35", icon: HandPlatter, label: "Penanak nasi" },
			{ id: "36", icon: SquareDot, label: "Meja makan" },
		],
	},
	{
		id: "k11",
		category: "Luar ruang",
		items: [
			{
				id: "37",
				icon: Trees,
				label: "Balkon pribadi",
				description: "Tempat untuk menikmati pemandangan atau juga merokok.",
			},
			{
				id: "38",
				icon: Trees,
				label: "Teras",
				description: "Tempat untuk menikmati pemandangan atau juga merokok.",
			},
			{ id: "39", icon: Trees, label: "Balkon bersama" },
		],
	},
	{
		id: "k12",
		category: "Layanan berbayar tambahan (hubungi cs untuk ketersediaan)",
		items: [
			{ id: "40", icon: WashingMachine, label: "Laundry" },
			{ id: "41", icon: Sparkle, label: "Layanan kebersihan" },
			{
				id: "42",
				icon: Film,
				label: "Videografer",
				description: "Untuk mendokumentasikan kegiatan anda saat liburan",
			},
			{
				id: "43",
				icon: Camera,
				label: "Fotografer",
				description: "Untuk mendokumentasikan kegiatan anda saat liburan",
			},
			{
				id: "44",
				icon: Calendar,
				label: "Menginap jangka panjang diizinkan",
				description: "Mengizinkan masa menginap 28 hari atau lebih",
			},
			{ id: "45", icon: Hand, label: "Pijat tradisional" },
			{
				id: "46",
				icon: Cake,
				label: "Dekorasi",
				description:
					"Dekorasi untuk pesta kecil, gathering, atau pesta ulang tahun",
			},
			{ id: "47", icon: Car, label: "Travel dan tur" },
			{ id: "48", icon: Beef, label: "BBQ set" },
			{ id: "49", icon: EggFried, label: "Breakfast" },
			{ id: "50", icon: HandPlatter, label: "Catering" },
		],
	},
	{
		id: "k13",
		category: "Tempat terdekat",
		items: [
			{ id: "51", icon: GraduationCap, label: "Universitas" },
			{
				id: "52",
				icon: Binoculars,
				label: "Wisata",
				description:
					"Museumku Gerabah, Chocolate Monggo Factory & Museum, Puncak Bibis, Goa Selarong, Pantai Bantul, dan masih banyak lagi",
			},
			{ id: "53", icon: HandPlatter, label: "Tempat kuliner terkenal" },
			{
				id: "54",
				icon: Cross,
				label: "Fasilitas kesehatan",
				description: "Puskesmas Kasihan, PKU Gamping",
			},
			{ id: "55", icon: ShoppingCart, label: "Swalayan" },
			{ id: "56", icon: MoonStar, label: "Masjid" },
		],
	},
	{
		id: "k14",
		category: "Tidak termasuk",
		items: [
			{ id: "57", icon: CircleX, label: "Tidak boleh: Merokok di dalam" },
			{ id: "58", icon: CircleX, label: "Tidak boleh: Berpesta besar" },
			{ id: "59", icon: CircleX, label: "Tidak tersedia: Pemanas ruangan" },
			{
				id: "60",
				icon: CircleX,
				label: "Tidak boleh: Membawa hewan peliharaan",
			},
		],
	},
];
